/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package idjit

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class AppTest {
    @Test
    fun testAppHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }

    @Test
    fun testParseLoe() {
        assertEquals(7, parseLoe("1w"))
        assertEquals(463, parseLoe("1d3m1y1w"))
    }
}
