/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package idjit

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

val timeUnits = mapOf("d" to 1L, "w" to 7L, "m" to 30L, "y" to 365L)
const val LOE_REGEX = "\\s*(?:(\\d+)\\s*([ymwd]))\\s*"

fun parseLoe(s: String): Long = Regex(LOE_REGEX)
    .findAll(s)
    .fold(0L) { days, m ->
        days + m.groups
            .toList()
            .drop(1)
            .map { it!!.value }
            .let {
                it[0].toLong() * timeUnits.getValue(it[1])
            }
    }

fun main(args: Array<String>) {
    when (args[0]) {
        "init" -> doInit()
        "add" -> doAdd(args)
    }
}
fun doAdd(args: Array<String>) {
    Db().use {
        val t = Task(args[1], args[2])
        it.insertTask(t)
    }
}

fun doInit() {

}

