/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package idjit

import java.sql.Timestamp
import java.time.Duration
import java.time.Instant
import java.time.temporal.ChronoUnit

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

data class Task(val loe: String) {

    val eta: Timestamp
        get() = Duration
            .ofDays(parseLoe(loe))
            .let {
                Timestamp.from(
                    Instant
                        .now()
                        .truncatedTo(ChronoUnit.DAYS)
                        .plus(it)
                )
            }

}

val timeUnits = mapOf("d" to 1L, "w" to 7L, "m" to 30L, "y" to 365L)
const val LOE_REGEX = "\\s*(?:(\\d+)\\s*([ymwd]))\\s*"

fun parseLoe(s: String): Long = Regex(LOE_REGEX)
    .findAll(s)
    .fold(0L) { days, m ->
        days + m.groups
            .toList()
            .drop(1)
            .map { it!!.value }
            .let {
                it[0].toLong() * timeUnits.getValue(it[1])
            }
    }

fun main(args: Array<String>) {
    println(App().greeting)
}
